[project]
name = "notebook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "azure-identity>=1.25.0",
    "azure-storage-blob>=12.26.0",
    "faker>=37.8.0",
    "pandas>=2.3.2",
    "reportlab>=4.4.3",
]
